spring:
  application:
    name: gallery-service
#  security:
#    user:
#      name: udpt
#      password: udpt2024
server:
  port: 8002
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


